/*
 * Copyright (c) 2023, Patrick Wilmes <patrick.wilmes@bit-lake.com>
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */
package internal

import (
	"strconv"
)

type note struct {
	Id   int    `json:"id"`
	IId  int    `json:"merge_request_iid"`
	Body string `json:"body"`
}

func PostNote(mrId int, accessToken string) error {
	note := note{
		Id:   26177235,
		IId:  mrId,
		Body: "Your Merge requests contains commits that are violating our commit guidelines! Please fix! - This message was generated by a bot",
	}
	return ExecuteWriteRequest(PostRequest, UrlForPostingANoteToAnMR(ProjectId, strconv.Itoa(mrId), accessToken), note)
}
